/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LiabraryProjectManagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nikhil
 */
public class Bookissuedd extends javax.swing.JFrame {

    /**
     * Creates new form BookIssuedd
     */
    DefaultTableModel mod;
    public Bookissuedd() {
        initComponents();
        bname.addItem("Select Book");
        bname.addItem("Physics");
        bname.addItem("Chemistry");
        bname.addItem("Biology");
        bname.addItem("Maths");
        bname.addItem("Python");
        bname.addItem("Java Book");
        bname.addItem("C++");
        bname.addItem("The Call of the Wild");
         bname.addItem("Lord of the Flies");
          bname.addItem("The Stranger"); bname.addItem("The Jungle");
           bname.addItem("Charlotte's Web");
            bname.addItem("Catch-22");
             bname.addItem("Mrs. Dalloway");
              bname.addItem("The Magician's Nephew");
               bname.addItem("The Good Earth");
          

       //updatebook();
       // calculateTotalBooks();
        
        setbookissued();
    }

 
   
    

    public void Clear() {
       
        bname.setSelectedItem(" ");
        txsid.setText(" ");
        txname.setText(" ");
        isuedatechoos.setDate(null);
        duedatechooser.setDate(null);
        JOptionPane.showMessageDialog(null, "Form Not Clear");
    }

    public void setbookissued() {

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from register1");

            while (rs.next()) {
                String ids = rs.getString("sid");
                String bookname = rs.getString("bname");
               
                String studentname = rs.getString("name");
                String issue = rs.getString("issuedate");
                //isuedatechoos.setDateFormatString(issue);
                String due = rs.getString("duedate");
                //duedatechooser.setDateFormatString(due);

                Object[] ob = {ids, bookname, studentname, issue, due};
                mod = (DefaultTableModel) jTable1.getModel();

                mod.addRow(ob);
            }
        } catch (Exception ex) {
            System.out.println("" + ex);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txsid = new javax.swing.JTextField();
        txname = new javax.swing.JTextField();
        duedatechooser = new com.toedter.calendar.JDateChooser();
        isuedatechoos = new com.toedter.calendar.JDateChooser();
        issuebtn = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        bname = new javax.swing.JComboBox();
        search = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        updatebtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totbooks = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Book Issue");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 0, 200, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Book Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 170, 180, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Student Id");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 90, 180, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Issue Date");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 330, 180, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Student Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 250, 180, 40);
        jPanel1.add(txsid);
        txsid.setBounds(210, 90, 260, 40);

        txname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnameActionPerformed(evt);
            }
        });
        jPanel1.add(txname);
        txname.setBounds(210, 250, 260, 40);

        duedatechooser.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(duedatechooser);
        duedatechooser.setBounds(210, 410, 260, 40);

        isuedatechoos.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(isuedatechoos);
        isuedatechoos.setBounds(210, 330, 260, 40);

        issuebtn.setIcon(new javax.swing.ImageIcon("D:\\images in java\\icons8-issue-outline-color\\icons8-issue-32.png")); // NOI18N
        issuebtn.setText("Issue");
        issuebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuebtnActionPerformed(evt);
            }
        });
        jPanel1.add(issuebtn);
        issuebtn.setBounds(40, 540, 100, 40);

        closebtn.setIcon(new javax.swing.ImageIcon("D:\\images in java\\icons8-close-ios-17-filled\\icons8-close-32.png")); // NOI18N
        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        jPanel1.add(closebtn);
        closebtn.setBounds(190, 540, 100, 40);

        clearbtn.setIcon(new javax.swing.ImageIcon("D:\\images in java\\icons8-clear-search-dotted\\icons8-clear-search-32.png")); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearbtn);
        clearbtn.setBounds(330, 540, 100, 40);

        bname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnameActionPerformed(evt);
            }
        });
        jPanel1.add(bname);
        bname.setBounds(210, 170, 260, 40);

        search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(530, 90, 90, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stutent Id", "Book Name", "Student Name", "Issue Date", "Due Date"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(120, 620, 452, 140);

        updatebtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(updatebtn);
        updatebtn.setBounds(480, 540, 90, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Total Books");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 480, 180, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Due Date");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 410, 180, 40);

        totbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totbooksActionPerformed(evt);
            }
        });
        jPanel1.add(totbooks);
        totbooks.setBounds(210, 480, 260, 40);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 2101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void issuebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuebtnActionPerformed
        // TODO add your handling code 
        

        
        
        
         
        
try {
            Date issued = isuedatechoos.getDate();
            DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            String issue = formatter.format(issued);

            Date dued = duedatechooser.getDate();
            DateFormat formater = new SimpleDateFormat("dd/MM/yyyy");
            String due = formater.format(dued);
            Class.forName("com.mysql.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
                String sql = "UPDATE register1 SET bname = '"+bname.getSelectedItem()+"', duedate ='"+due+"' , issuedate ='"+issue+"' , totalbooks = totalbooks - 1 WHERE sid = '"+txsid.getText()+"'";
            PreparedStatement pst = con.prepareStatement(sql);
           pst.executeUpdate();
            
            String updateSql = "update books set quantity = quantity - 1 WHERE bname = '"+bname.getSelectedItem()+"'";
            PreparedStatement pst1=con.prepareStatement(updateSql);
            int i=pst1.executeUpdate();
            if(i>0){
             JOptionPane.showMessageDialog(null, "Book Issued");   
            }else{
                
            }
            
            
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Book Not Issued");
            System.out.println("" + ex);
        }
    }//GEN-LAST:event_issuebtnActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
        Clear();


    }//GEN-LAST:event_clearbtnActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try {
            int search = 0;
            Class.forName("com.mysql.jdbc.Driver"); // Use the correct driver class name
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");

            String sql = "select * from register1 where sid = '"+txsid.getText()+"'";
            PreparedStatement pst = con.prepareStatement(sql);
           
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                search = 1;

                String s = rs.getString("name");
                txname.setText(s);
                String sql1 = "Select * from register1 where sid='"+txsid.getText()+"'";
                PreparedStatement pst1 = con.prepareStatement(sql1);
                

                ResultSet rs1 = pst1.executeQuery();

                if (rs1.next()) {
                    
                    
                    String bookname = rs1.getString("bname");
                    bname.setSelectedItem(bookname);

                    String issue = rs1.getString("issuedate");
                    Date date = new SimpleDateFormat("dd/MM/yyyy").parse(issue);
                    isuedatechoos.setDate(date);
                    String due = rs1.getString("duedate");
                    Date dued = new SimpleDateFormat("dd/MM/yyyy").parse(due);
                    duedatechooser.setDate(dued);

                } else {

                }
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Student ID");
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }

    }//GEN-LAST:event_searchActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        try {
            Date issued = isuedatechoos.getDate();
            DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            String issue = formatter.format(issued);

            Date dued = duedatechooser.getDate();
            DateFormat formater = new SimpleDateFormat("dd/MM/yyyy");
            String due = formater.format(dued);
            Class.forName("com.mysql.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
            String sql = "update register1 set name='" + txname.getText() + "',bname='" + bname.getSelectedItem() + "',issuedate='" + issue + "',duedate='" + due + "' where sid='" + txsid.getText() + "'";

            PreparedStatement pst = con.prepareStatement(sql);
            int update = pst.executeUpdate();
            if (update > 0) {
                JOptionPane.showMessageDialog(null, "Updated");
               
                bname.setSelectedItem("Select Book");
                txsid.setText("");
                txname.setText("");
                isuedatechoos.setDate(null);
                duedatechooser.setDate(null);
            } else {
                JOptionPane.showMessageDialog(null, "Not Updated");
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Form Not Updated");
            System.out.println("" + ex);
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void bnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnameActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_bnameActionPerformed

    private void txnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnameActionPerformed

    private void totbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totbooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totbooksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bookissuedd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bookissuedd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bookissuedd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bookissuedd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookissuedd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bname;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton closebtn;
    private com.toedter.calendar.JDateChooser duedatechooser;
    private javax.swing.JButton issuebtn;
    private com.toedter.calendar.JDateChooser isuedatechoos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton search;
    private javax.swing.JTextField totbooks;
    private javax.swing.JTextField txname;
    private javax.swing.JTextField txsid;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables

   
   
    

   

