/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LiabraryProjectManagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Nikhil
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        newstubtn = new javax.swing.JButton();
        statatics = new javax.swing.JButton();
        bookisudbtn = new javax.swing.JButton();
        returnbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setBackground(new java.awt.Color(102, 255, 153));
        logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logout.setText("LogOut");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 140, 50));

        newstubtn.setBackground(new java.awt.Color(153, 255, 153));
        newstubtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newstubtn.setText("New Student");
        newstubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newstubtnActionPerformed(evt);
            }
        });
        jPanel1.add(newstubtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 50));

        statatics.setBackground(new java.awt.Color(102, 255, 153));
        statatics.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statatics.setText("Statastics");
        statatics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stataticsActionPerformed(evt);
            }
        });
        jPanel1.add(statatics, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, 50));

        bookisudbtn.setBackground(new java.awt.Color(102, 255, 153));
        bookisudbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bookisudbtn.setText("Issue Book");
        bookisudbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookisudbtnActionPerformed(evt);
            }
        });
        jPanel1.add(bookisudbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 140, 50));

        returnbtn.setBackground(new java.awt.Color(102, 255, 153));
        returnbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        returnbtn.setText("Return Book");
        returnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbtnActionPerformed(evt);
            }
        });
        jPanel1.add(returnbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 140, 50));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newstubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newstubtnActionPerformed
        // TODO add your handling code here:
        RegistrationForm o = new RegistrationForm();
        o.setVisible(true);
    }//GEN-LAST:event_newstubtnActionPerformed

    private void bookisudbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookisudbtnActionPerformed
        // TODO add your handling code here:
        Bookissuedd b = new Bookissuedd();
        b.setVisible(true);
        
    }//GEN-LAST:event_bookisudbtnActionPerformed

    private void returnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbtnActionPerformed
        // TODO add your handling code here:
        BookReturned returnd = new BookReturned();
        returnd.setVisible(true);
    }//GEN-LAST:event_returnbtnActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        try {

            int choice = JOptionPane.showConfirmDialog(null, "Do You Want Continue?");
            if (choice == JOptionPane.YES_OPTION) {
                
                LogIn i=new LogIn();
                i.setVisible(true);
                //setVisible(false);
                this.dispose();
            } else {
                
            }

            

            
        } catch (Exception ex) {
            System.out.println("" + ex);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void stataticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stataticsActionPerformed
        // TODO add your handling code here:
        Statastics s=new Statastics();
        s.setVisible(true);
    }//GEN-LAST:event_stataticsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookisudbtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JButton newstubtn;
    private javax.swing.JButton returnbtn;
    private javax.swing.JButton statatics;
    // End of variables declaration//GEN-END:variables
}
