/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LiabraryProjectManagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Nikhil
 */
public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
        courcomb.addItem("Select Course");
        courcomb.addItem("BCA");
         courcomb.addItem("MCA");
          courcomb.addItem("BBA");
           courcomb.addItem("MBA");
            courcomb.addItem("BVOCATIONAL");
            
            
            
            semcomb.addItem("Select Year");
            semcomb.addItem("I Year");
            semcomb.addItem("II Year");
            semcomb.addItem("III Year");
            semcomb.addItem("IV Year");
            semcomb.addItem("V Year");
            semcomb.addItem("VI Year");
            
            
            
            txbran.addItem("Select Branch");
            txbran.addItem("ITI");
            txbran.addItem("CSE");
            txbran.addItem("Mechanical");
            txbran.addItem("IT");
            txbran.addItem("Civil");
            txbran.addItem("Electrical");

            
    }
public void Clear(){

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txAlternum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        semcomb = new javax.swing.JComboBox();
        txbran = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tempaddtx = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        permnatx = new javax.swing.JTextArea();
        txname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tphone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        courcomb = new javax.swing.JComboBox();
        closebtn = new javax.swing.JButton();
        savebtn1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txfname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txemail1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1302, 802));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Student Registration Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 410, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Course Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Student Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 300, 60));

        txid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txidActionPerformed(evt);
            }
        });
        jPanel1.add(txid, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 310, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Student Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 130, 30));

        txAlternum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txAlternumActionPerformed(evt);
            }
        });
        jPanel1.add(txAlternum, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 180, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Semester");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 100, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Alternate Number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 170, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Father Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 130, 30));

        jPanel1.add(semcomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 100, -1));

        jPanel1.add(txbran, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 300, 30));

        tempaddtx.setColumns(20);
        tempaddtx.setRows(5);
        jScrollPane2.setViewportView(tempaddtx);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 310, 70));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Permanant Address");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 190, 30));

        permnatx.setColumns(20);
        permnatx.setRows(5);
        jScrollPane3.setViewportView(permnatx);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 310, 70));

        txname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnameActionPerformed(evt);
            }
        });
        jPanel1.add(txname, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 310, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Phone");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 160, 30));

        tphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tphoneActionPerformed(evt);
            }
        });
        jPanel1.add(tphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 180, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Temperrory Address");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 190, 30));

        jPanel1.add(courcomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 100, -1));

        closebtn.setIcon(new javax.swing.ImageIcon("D:\\images in java\\icons8-close-ios-17-filled\\icons8-close-50.png")); // NOI18N
        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        jPanel1.add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 750, 140, 50));

        savebtn1.setIcon(new javax.swing.ImageIcon("D:\\images in java\\icons8-save-color\\icons8-save-48.png")); // NOI18N
        savebtn1.setText("Save");
        savebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(savebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 750, 150, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Branch");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 160, 30));

        txfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfnameActionPerformed(evt);
            }
        });
        jPanel1.add(txfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 310, 50));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Enter Email");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 160, 30));

        txemail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txemail1ActionPerformed(evt);
            }
        });
        jPanel1.add(txemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 310, 50));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1254, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txidActionPerformed

    private void txAlternumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txAlternumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txAlternumActionPerformed

    private void txnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnameActionPerformed

    private void tphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tphoneActionPerformed

    private void savebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtn1ActionPerformed
        // TODO add your handling code here:
         try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root" ,"");
        String sql = "insert into register1 (sid, name, fname, course, sem, paddress, tempadd, phone, alternum, branch, email) VALUES ('" + txid.getText() + "', '" + txname.getText() + "', '" + txfname.getText() + "', '" + courcomb.getSelectedItem() + "', '" + semcomb.getSelectedItem() + "', '" + permnatx.getText() + "', '" + tempaddtx.getText() + "', '" + tphone.getText() + "', '" + txAlternum.getText() + "', '" + txbran.getSelectedItem() + "', '" + txemail1.getText() + "')";        
        PreparedStatement pst=con.prepareStatement(sql);
        int s= pst.executeUpdate();
        if(s>0){
        JOptionPane.showMessageDialog(null, "Record Saved");
        }else{
        JOptionPane.showMessageDialog(null, "Record Not Saved");
        }
        txid.setText("");
        txname.setText("");
        txfname.setText("");
        courcomb.setSelectedItem("Select Course");
        semcomb.setSelectedItem("Select Semester");
        permnatx.setText("");
        tempaddtx.setText("");
        tphone.setText("");
        txAlternum.setText("");
        txbran.setSelectedItem("Select Branch");
        
        }catch(Exception ex){
            
            System.out.println("cnh"+ex);
            JOptionPane.showMessageDialog(null, "Please Check ID it is Already Exist");
        }
    }//GEN-LAST:event_savebtn1ActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void txfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfnameActionPerformed

    private void txemail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txemail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txemail1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebtn;
    private javax.swing.JComboBox courcomb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea permnatx;
    private javax.swing.JButton savebtn1;
    private javax.swing.JComboBox semcomb;
    private javax.swing.JTextArea tempaddtx;
    private javax.swing.JTextField tphone;
    private javax.swing.JTextField txAlternum;
    private javax.swing.JComboBox txbran;
    private javax.swing.JTextField txemail1;
    private javax.swing.JTextField txfname;
    private javax.swing.JTextField txid;
    private javax.swing.JTextField txname;
    // End of variables declaration//GEN-END:variables
}
