/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LiabraryProjectManagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Nikhil
 */
public class Statastics extends javax.swing.JFrame {

    /**
     * Creates new form StatasticsN
     */
    DefaultTableModel mod;

    public Statastics() {
        initComponents();
        setbookissued();

        SetReturnbook();
    }

    public void setbookissued() {

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from register1");

            while (rs.next()) {
                String ids = rs.getString("sid");
                String name=rs.getString("name");
                String fname=rs.getString("fname");
                String cou=rs.getString("course");
                String sem=rs.getString("sem");
                String paddress=rs.getString("paddress");
                String taddress=rs.getString("tempadd");
                String phone=rs.getString("phone");
                String alternum=rs.getString("alternum");
                String branch=rs.getString("branch");
                String email=rs.getString("email");
                String bname=rs.getString("bname");
                String issue = rs.getString("issuedate");

                String due = rs.getString("duedate");
                
                String tot=rs.getString("totalbooks");
                Object[] ob = {ids, name,fname,cou,sem,paddress,taddress,phone,alternum,branch,email,bname,issue,due,tot};
                mod = (DefaultTableModel) table1.getModel();

                mod.addRow(ob);
            }
        } catch (Exception ex) {
            System.out.println("" + ex);
        }
    }

    public void SetReturnbook() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from register1");

            while (rs.next()) {
                String ids = rs.getString("sid");
                String name=rs.getString("name");
                String fname=rs.getString("fname");
                String cou=rs.getString("course");
                String sem=rs.getString("sem");
                String paddress=rs.getString("paddress");
                String taddress=rs.getString("tempadd");
                String phone=rs.getString("phone");
                String alternum=rs.getString("alternum");
                String branch=rs.getString("branch");
                String email=rs.getString("email");
                String bname=rs.getString("bname");
                String issue = rs.getString("issuedate");

                String due = rs.getString("duedate");
                String return1=rs.getString("returndate");
                String tot=rs.getString("totalbooks");
 
                Object[] ob = {ids, name,fname,cou,sem,paddress,taddress,phone,alternum,branch,email,bname,issue,due,return1,tot};
                mod = (DefaultTableModel) table2.getModel();

                mod.addRow(ob);
            }
        } catch (Exception ex) {
            System.out.println("" + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        view2 = new javax.swing.JButton();
        view1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 800));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(null);

        table1.setBackground(new java.awt.Color(204, 204, 255));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "Studet Name", "Father Name", "Course", "Semester", "Permanent Address", "Temparory Address", "Phone", "AlterNate Number", "Branch", "Email Id", "Book Name", "Issue Date", "DueDate", "TotalBooks"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        table1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                table1ComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(table1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(370, 80, 1400, 240);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Return Table");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(590, 330, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Issue Table");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(580, 20, 170, 30);

        table2.setBackground(new java.awt.Color(204, 204, 255));
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "Student Name", "Father Name", "Course", "Semester", "Permanent Address", "Temparary Address", "Phone", "AlterNateNumber", "Branch", "Email Id", "Book Name", "Issue Date", "Due Date", "Return Date Book", "Total Books"
            }
        ));
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table2);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(370, 380, 1410, 250);

        view2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        view2.setText("View");
        view2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view2ActionPerformed(evt);
            }
        });
        jPanel1.add(view2);
        view2.setBounds(50, 390, 100, 50);

        view1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        view1.setText("View");
        view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1ActionPerformed(evt);
            }
        });
        jPanel1.add(view1);
        view1.setBounds(50, 80, 100, 50);

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(570, 740, 250, 90);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 3143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_table1ComponentShown
        // TODO add your handling code here:
        try {
            /* Class.forName("com.mysql.jdbc.Driver");
             Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root" ,"");
             String sql = "SELECT issued_date.bid,bname,issued_date.studentid,issued_date.sname,issued_date.issuedate,issued_date.duedate where from issued_book 'Yes'";
        
        

             PreparedStatement pst=con.prepareStatement(sql);
        
             ResultSet rs=pst.executeQuery();
             table1.setModel(DbUtils.resultSetToTableModel(rs));
        
        
             String sql1="select * from return_table";
             PreparedStatement pst1=con.prepareStatement(sql1);
             ResultSet rs1=pst1.executeQuery();
             table2.setModel(DbUtils.resultSetToTableModel(rs1));
             */

        } catch (Exception ex) {
            System.out.println("" + ex);
        }

    }//GEN-LAST:event_table1ComponentShown

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_table1MouseClicked

    private void view2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view2ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
            String sql = "select * from register1";
            PreparedStatement pst1 = con.prepareStatement(sql);
            ResultSet rs = pst1.executeQuery();
            table2.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception ex) {
            System.out.println("" + ex);
        }
    }//GEN-LAST:event_view2ActionPerformed

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        // TODO add your handling code here:
        /*DefaultTableModel deftable=(DefaultTableModel)table1.getModel();
        
         if(table1.getSelectedRowCount()==1){
         deftable.removeRow(table1.getSelectedRow());
         }else{
         if(table1.getSelectedRow()==0){
         JOptionPane.showMessageDialog(null, "Table is Empty");
         }else{
         JOptionPane.showMessageDialog(null, "Single table select");
         }*/
        //}
    }//GEN-LAST:event_table2MouseClicked

    private void view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
            String sql = "select * from register1";
            PreparedStatement pst = con.prepareStatement(sql);

            ResultSet rs = pst.executeQuery();
            table1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            System.out.println("" + ex);
        }
    }//GEN-LAST:event_view1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:Menu menu = new Menu();
        Menu menu = new Menu();
        menu.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statastics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statastics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statastics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statastics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statastics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JButton view1;
    private javax.swing.JButton view2;
    // End of variables declaration//GEN-END:variables
}
